# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be488831263c8ddbf9f0f01e6a1fa234620808f471afe572a39a5d2c91e9e8a902afcff152ac03f102132b3261db862a006528febb780b0e1e8673ff95fc1fe6

test:
  secret_key_base: acb2cbb33ae0d02be0d6ea51729266999e5df04bc091174b5f77abbde9034a318bd00c2b19ae5425149f7423ca42b1b60be0b82b501a026bea656c30effaf8d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
